ecommerce/urls.py
from django.urls import path


from . import views

app_name = 'ecommerce'


urlpatterns = [
    path('', views.home, name="home"),
    path('product/<int:id>/', views.product, name="details"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings


def my_view(request):
    return HttpResponse('Teste')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    # path('test', include('ecommerce.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/models.py
from django.contrib.auth.models import User
from django.db import models



class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=65)
    slug = models.SlugField()
    type = models.CharField(max_length=65)
    sale_price = models.IntegerField()
    product_details = models.TextField(max_length=2000)
    product_details_is_html = models.BooleanField(default =True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default =True)
    cover = models.ImageField(upload_to='product/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

ecommerce/views.py
from django.http import HttpResponse
from django.shortcuts import render
from utils.product.factory import make_product
# Create your views here.


def home(request):
    return render(request, 'pages/home/home.html', context={
        'name':'Ecommerce',
        'products': [make_product() for _ in range(10)],        
        })


def product(request, id):
    return render(request, 'pages/details/details.html', context={
        'name':'Ecommerce',
        'product': make_product(),
        'is_detail_page': True,
        })

ecommerce/templates/components/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css" integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css" integrity="sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/solid.min.css" integrity="sha512-pZlKGs7nEqF4zoG0egeK167l6yovsuL8ap30d07kA5AJUq+WysFlQ02DLXAmN3n0+H3JVz5ni8SJZnrOaYXWBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'ecommerce/css/global.css' %}">

ecommerce/templates/components/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url "ecommerce:home" %}">
                <i class="fa-solid fa-cart-shopping main-logo-icon"></i>
                <span>{{name}}</span>
            </a>                
        </h1>
    </div>
</header>

ecommerce/templates/components/product.html
<div class="product product-list-item">
    <div class="product-image">
        <a href="{% url "ecommerce:details" product.id %}">
            <img src="{{ product.cover.url }}" alt="temporario">
        </a>
    </div>
    <div class="product-title-container">
        
            <h2 class="product-title">
                <a href="{% url "ecommerce:details" product.id %}">{{ product.title }}</a>
            </h2>
        
    </div>
    <div class="product-seller">
        <span class="product-seller-item">
            <i class="fas fa-user"></i>
            {{ product.author.first_name }} {{ product.author.last_name }}
        </span>
        <br>
        <span class="product-seller-item">
            <i class="fas fa-calendar-alt"></i>
            {{ product.created_at|date:"d/m/Y"}} às {{ product.created_at|date:"H:i:s"}}
        </span>
        <br>
        <span class="product-seller-item">
            <a href="/products/category/amigurumi/">
                <i class="fas fa-layer-group"></i>
                <span>{{ product.category.name }}</span>
            </a>
        </span>
    </div>
    <div class="product-content">
        <p>{{ product.description }}</p>
    </div>
    
    <div class="product-meta-container">
        <div class="product-meta product-category">
            <h3 class="product-meta-title">
                <i class="fa-solid fa-barcode"></i>
                {{ product.category.name }}
            </h3>
            <div class="product-meta-text">
                {{ product.type }}
            </div>
        </div>
        <div class="product-meta product-price">
            <h3 class="product-meta-title">
                <i class="fa-solid fa-tag"></i> 
                Preço
            </h3>
            <div class="product-meta-text">
                R$ {{ product.sale_price}},99
            </div>
        </div>
    </div>

    {% if is_detail_page is not True  %}
    <footer class="product-footer">
        <a class="product-read-more button button-dark button-full-width" href="{% url "ecommerce:details" product.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="ecommerce:details">{{ product.product_details }}</div>
    {% endif %}

</div>

ecommerce/templates/components/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>
</div>

ecommerce/templates/pages/details/details.html
{% extends "global/layout/base.html" %}

{% block title %}Details |{% endblock title %}


{% block content %}
<div class="main-content main-content-detail container">
    
    {% include "components/product.html" %}
    
</div>
{% endblock content %}

ecommerce/templates/pages/home/home.html
{% extends "global/layout/base.html" %}

{% block title %}Home |{% endblock title %}

{% block content %}

<div class="main-content main-content-list container">
    
    {% for product in products %}
        {% include "components/product.html" %}
    {% endfor %}

    
</div>

{% endblock content %}